// 型付き小テストデータ → Google Form(Apps Script) 変換ツール
//
// 使い方:
//   node tools/quiz-to-google-form.ts <quiz.ts|quiz.json> [output.gs]
//   npm run gen:form -- docs/exercises/lecture7-interface.quiz.ts
//
// 入力は tools/quiz-types.ts の Quiz 型に沿った構造化データ（正規ソース）。
// 出力された .gs を script.google.com に貼り付けて createForm() を実行すると、
// 正解を反映した採点付きQuiz(Google Form)が生成される。

import { writeFileSync } from "node:fs";
import { basename, dirname, isAbsolute, join, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import type { Quiz, QuizQuestion } from "./quiz-types.ts";

// 正解ラベル("A","B",...)を0始まりのindexへ。範囲外なら例外。
function answerIndex(q: QuizQuestion, i: number): number {
  const idx = q.answer.trim().toUpperCase().charCodeAt(0) - "A".charCodeAt(0);
  if (idx < 0 || idx >= q.choices.length) {
    throw new Error(`Q${i + 1}: 正解 "${q.answer}" が選択肢(${q.choices.length}個)の範囲外`);
  }
  return idx;
}

function validate(quiz: Quiz): void {
  if (!quiz || typeof quiz.title !== "string" || !Array.isArray(quiz.questions)) {
    throw new Error("Quiz 型ではありません（title / questions を確認）");
  }
  quiz.questions.forEach((q, i) => {
    if (typeof q.q !== "string" || !q.q.trim()) throw new Error(`Q${i + 1}: 設問文 q が空`);
    if (!Array.isArray(q.choices) || q.choices.length < 2) {
      throw new Error(`Q${i + 1}: choices は2つ以上必要`);
    }
    answerIndex(q, i); // 範囲チェック
  });
}

function buildAppsScript(quiz: Quiz, source: string): string {
  const payload = quiz.questions.map((q, i) => ({
    title: `Q${i + 1}. ${q.q}`,
    points: q.points ?? 1,
    choices: q.choices.map((text, ci) => ({ text, correct: ci === answerIndex(q, i) })),
  }));

  const description =
    quiz.description ?? `${quiz.title}（全${quiz.questions.length}問・選択式）\n自動採点付きQuiz。`;

  return `// AUTO-GENERATED by tools/quiz-to-google-form.ts
// Source: ${source}
//
// 手順:
//   1. https://script.google.com で新規プロジェクトを作成
//   2. このコードを丸ごと貼り付け
//   3. 関数 createForm を選択して実行(初回は権限承認が必要)
//   4. 実行ログに出力される「編集URL / 回答URL」を開く

var FORM_TITLE = ${JSON.stringify(quiz.title)};
var FORM_DESCRIPTION = ${JSON.stringify(description)};
var QUESTIONS = ${JSON.stringify(payload, null, 2)};

function createForm() {
  var form = FormApp.create(FORM_TITLE);
  form.setIsQuiz(true);
  form.setDescription(FORM_DESCRIPTION);
  // 成績は既定の「送信直後に表示」のまま使う（Apps Scriptに変更APIはない）。
  // Workspaceアカウントでは既定でメール収集がONになるため、明示的にOFFにする。
  form.setEmailCollectionType(FormApp.EmailCollectionType.DO_NOT_COLLECT);

  QUESTIONS.forEach(function (q) {
    var item = form.addMultipleChoiceItem();
    item.setTitle(q.title);
    item.setPoints(q.points);
    item.setRequired(true);
    item.setChoices(
      q.choices.map(function (c) {
        return item.createChoice(c.text, c.correct);
      })
    );
  });

  Logger.log("編集URL: " + form.getEditUrl());
  Logger.log("回答URL: " + form.getPublishedUrl());
}
`;
}

async function loadQuiz(input: string): Promise<Quiz> {
  const abs = isAbsolute(input) ? input : resolve(process.cwd(), input);
  if (input.endsWith(".json")) {
    const { readFileSync } = await import("node:fs");
    return JSON.parse(readFileSync(abs, "utf8")) as Quiz;
  }
  // .ts / .js は動的import。named export `quiz` か default export を受け付ける。
  const mod = (await import(pathToFileURL(abs).href)) as { quiz?: Quiz; default?: Quiz };
  const quiz = mod.quiz ?? mod.default;
  if (!quiz) throw new Error(`${input} に export const quiz / default export が見つかりません`);
  return quiz;
}

async function main() {
  const [, , input, output] = process.argv;
  if (!input) {
    console.error("使い方: node tools/quiz-to-google-form.ts <quiz.ts|quiz.json> [output.gs]");
    process.exit(1);
  }

  const quiz = await loadQuiz(input);
  validate(quiz);

  const gs = buildAppsScript(quiz, basename(input));
  const out =
    output ?? join(dirname(input), `${basename(input).replace(/\.(quiz\.)?(ts|js|json)$/, "")}.form.gs`);
  writeFileSync(out, gs, "utf8");

  console.log(`✅ 生成: ${out}`);
  console.log(`   設問数: ${quiz.questions.length}（全問に正解を設定）`);
  console.log("   次: script.google.com に貼り付けて createForm() を実行");
}

main().catch((e) => {
  console.error(`エラー: ${e instanceof Error ? e.message : e}`);
  process.exit(1);
});
